### ISSUE TITLE
Advanced Lightsabers

### ISSUE THREAD

**Issue by ConnallM** [wormzjl/Project-PFAA#33]
When installing the pack on ATL launcher it is unable to download the mod from curseforge and immediately terminates the installation. It is a required mod so I am completely unable to download the pack from ATLauncher.

Error:

[12/01/2021 09:36:24 AM] Error trying to download AdvancedLightsabers-1.7.10-1.1.1.jar
[12/01/2021 09:36:24 AM] com.atlauncher.network.DownloadException: https://www.curseforge.com/minecraft/mc-mods/advanced-lightsabers/download/2387105/file request wasn't successful: Response{protocol=h2, code=403, message=, url=https://www.curseforge.com/minecraft/mc-mods/advanced-lightsabers/download/2387105/file}
	at com.atlauncher.network.Download.execute(Download.java:293)
	at com.atlauncher.network.Download.downloadFile(Download.java:545)
	at com.atlauncher.network.DownloadPool$Downloader.run(DownloadPool.java:122)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by cvera020** [comment]
Hi @ConnallM , this looks like a bug but an easy work-around is to download the troublesome JAR files and drop them into the /downloads folder where your AtLauncher.exe is located.

**So just download the JAR files from the following and place them in /downloads:
https://www.curseforge.com/minecraft/mc-mods/advanced-lightsabers/download/2387105/file
https://www.curseforge.com/minecraft/mc-mods/journeymap/download/2367916/file**

If you're still getting issues, check the /logs folder, open the latest-modified atlauncher.log, scroll towards the bottom and see what other DownloadException is occurring, and follow the same operation as above for those file URL links.
